title: Standard

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          submenu:
            type: structure
            label: Untermenu (Scroll)
            fields:
              link:
                label: Verlinkung zu Titel
                type: select
                options: query
                query:
                  fetch: page.main_content.form.toBlocks.filterBy("level", "in", ["h2", "h3"])
                  text: "{{ block.text }}" 
                  value: "{{ block.text.slug }}"
              title:
                label: Bezeichnung
                type: text
          cover:
            label: Cover-Bild
            type: files
            multiple: false
          main_content:
            label: Inhalt
            type: blocks
            fieldsets:
              - heading
              - text
              - list
              - image
              - video
              - list_details
              - group_start
              - accordion
              - group_end
              - gallery_caption
              - image_download
              - imageText
  sidebar:
    width: 1/3
    sections:
      #pages:
      #  type: pages
      #  template: default
      files:
        type: files

